spring.application.name=lab2_4
server.port=8090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=artem_2006
spring.datasource.url=jdbc:postgresql://localhost:5433/lab4-spring-jpa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false