server:
  port: 8091
  servlet:
    context-path: /

jwt:
  secret: secretikkhsd8ouu1234128937918912318768723694688123487678123    #${JWT_SECRET}
  expiration: 86400000 # 1 сутки

spring:
  freemarker:
    suffix: .ftlh
    template-loader-path: classpath:/templates
    request-context-attribute: rc

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: artem_2006
    url: jdbc:postgresql://localhost:5433/ORIS-lab-06
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    filter:
      dispatcher-types: REQUEST, ERROR, ASYNC